# Generated by Django 4.0.3 on 2022-05-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_hhuser_activate_key_hhuser_activate_key_expired_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'скилл',
                'verbose_name_plural': 'скиллы',
                'ordering': ('-name',),
            },
        ),
        migrations.RemoveField(
            model_name='hhuser',
            name='activate_key',
        ),
        migrations.RemoveField(
            model_name='hhuser',
            name='activate_key_expired',
        ),
    ]
