# Generated by Django 4.0.3 on 2022-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_hhuserprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hhuserprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='hhuser',
            name='skills',
            field=models.ManyToManyField(blank=True, to='authapp.skills', verbose_name='Скиллы'),
        ),
    ]
