# Generated by Django 4.0.3 on 2022-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_remove_hhuserprofile_skills_hhuser_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hhuserprofile',
            name='tagline',
        ),
        migrations.AddField(
            model_name='hhuserprofile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Хобби'),
        ),
        migrations.AddField(
            model_name='hhuserprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='hhuserprofile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='hhuserprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='Обо мне'),
        ),
    ]
